language: r
cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
matrix:
  include:
#  - r: oldrel
#    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
#  - r: release
#    os: osx
before_install:
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
- install_hdf5
- install_dynverse
install:
- install_cran remotes covr
- R -e 'install.packages("data.table")'
- install_withdeps
after_success:
 - R -e 'covr::codecov()'

